### PR TITLE
Add refreshReceipt API

### PR DESCRIPTION
**Pull request by jrouault**
## Minor
- Add `refreshReceipt` API to manually refresh the iOS receipt when needed (iOS)

poke @tbrebant @ronkorving

### CODE REVIEW

**Comment by ronkorving** [comment]
Is this the behavior Apple and apps tend to call "restorePurchases"?

**Comment by jrouault** [comment]
Not exactly. The receipt might sometimes be out of sync and `refreshReceipt` will simply ask Apple to send back the latest one. `restoreAllPurchases` will explicitely ask to restore previously completed transactions, such as non-consumable validated purchases.

**Comment by ronkorving** [comment]
If tested to work, LGTM

**Review by tbrebant — APPROVED** [review]
Looks good

**Pull request merged**
